# Generated by Django 4.2.20 on 2026-09-05 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkpoints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('benchmark_symbol', models.CharField(max_length=20)),
                ('checkpoint_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('checkpoint_as_of', models.DateTimeField()),
                ('current_as_of', models.DateTimeField()),
                ('current_received_at', models.DateTimeField()),
                ('benchmark_checkpoint_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('benchmark_current_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('stock_return', models.FloatField(default=0)),
                ('benchmark_return', models.FloatField(default=0)),
                ('residual_return', models.FloatField(default=0)),
                ('rolling_volatility', models.FloatField(default=0)),
                ('expected_gap_volatility', models.FloatField(default=0)),
                ('max_excursion_return', models.FloatField(default=0)),
                ('own_surprise_ratio', models.FloatField(default=0)),
                ('own_component_points', models.FloatField(default=0)),
                ('residual_volatility', models.FloatField(default=0)),
                ('expected_residual_gap_volatility', models.FloatField(default=0)),
                ('benchmark_divergence_ratio', models.FloatField(default=0)),
                ('benchmark_component_points', models.FloatField(default=0)),
                ('attention_score', models.PositiveIntegerField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('ROUTINE', 'Routine'), ('NEEDS_ATTENTION', 'Needs Attention'), ('VERIFY_DATA', 'Verify Data')], max_length=30)),
                ('is_reversal', models.BooleanField(default=False)),
                ('quality_status', models.CharField(default='FRESH', max_length=30)),
                ('explanation', models.TextField()),
                ('replay_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='checkpoints.itemcheckpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_receipts', to=settings.AUTH_USER_MODEL)),
                ('watchlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='watchlists.watchlistitem')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'watchlist_item', 'replay_index'], name='receipts_ch_user_id_c1a7c0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='changereceipt',
            constraint=models.UniqueConstraint(fields=('user', 'watchlist_item', 'checkpoint', 'replay_index'), name='unique_receipt_for_checkpoint_replay'),
        ),
    ]
