# Generated by Django 4.2.20 on 2026-09-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0002_itemcheckpoint_unique_checkpoint_user_item_replay'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changereceipt',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipts', to='checkpoints.itemcheckpoint'),
        ),
    ]
