# Generated by Django 4.2.20 on 2026-09-05 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('incident_type', models.CharField(choices=[('DELAYED', 'Delayed'), ('CONFLICT', 'Conflict'), ('OUT_OF_ORDER', 'Out Of Order'), ('MISSING_INTERVAL', 'Missing Interval'), ('MALFORMED', 'Malformed'), ('CORPORATE_ACTION', 'Corporate Action')], max_length=40)),
                ('description', models.TextField()),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('current_as_of', models.DateTimeField()),
                ('scenario_version', models.CharField(default='gapline-demo-v1', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('as_of', models.DateTimeField()),
                ('rolling_20d_volatility', models.FloatField()),
                ('benchmark_symbol', models.CharField(max_length=20)),
                ('residual_20d_volatility', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('as_of', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('quality_status', models.CharField(default='FRESH', max_length=30)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'as_of'], name='market_mark_symbol_cc040a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('as_of', models.DateTimeField()),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('provider', models.CharField(default='DemoReplayProvider', max_length=60)),
                ('is_benchmark', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'as_of'], name='market_mark_symbol_0b46e5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='marketbar',
            constraint=models.UniqueConstraint(fields=('symbol', 'as_of', 'provider'), name='unique_bar_symbol_asof_provider'),
        ),
    ]
