# Generated by Django 4.2.20 on 2026-09-06 08:14

from django.db import migrations, models


def collapse_replay_states(apps, schema_editor):
    ReplayState = apps.get_model("market", "ReplayState")
    states = list(ReplayState.objects.order_by("id"))
    for state in states[1:]:
        state.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(collapse_replay_states, migrations.RunPython.noop),
        migrations.AddField(
            model_name='replaystate',
            name='singleton_enforcer',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
