# Generated by Django 4.2.20 on 2026-09-05 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('checkpoint_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('benchmark_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('checkpoint_as_of', models.DateTimeField()),
                ('replay_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_checkpoints', to=settings.AUTH_USER_MODEL)),
                ('watchlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='watchlists.watchlistitem')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'watchlist_item', 'created_at'], name='checkpoints_user_id_53ecee_idx')],
            },
        ),
    ]
