# Generated by Django 4.2.20 on 2026-09-06 08:14

from django.db import migrations, models


def collapse_duplicate_checkpoints(apps, schema_editor):
    ItemCheckpoint = apps.get_model("checkpoints", "ItemCheckpoint")
    ChangeReceipt = apps.get_model("receipts", "ChangeReceipt")
    seen = {}
    for checkpoint in ItemCheckpoint.objects.order_by("user_id", "watchlist_item_id", "replay_index", "created_at", "id"):
        key = (checkpoint.user_id, checkpoint.watchlist_item_id, checkpoint.replay_index)
        canonical_id = seen.get(key)
        if canonical_id is None:
            seen[key] = checkpoint.id
            continue
        ChangeReceipt.objects.filter(checkpoint_id=checkpoint.id).update(checkpoint_id=canonical_id)
        checkpoint.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0001_initial'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(collapse_duplicate_checkpoints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='itemcheckpoint',
            constraint=models.UniqueConstraint(fields=('user', 'watchlist_item', 'replay_index'), name='unique_checkpoint_user_item_replay'),
        ),
    ]
